### PR TITLE
Adds functionality to request CC3000 MAC address

### PR DESCRIPTION
**Pull request by johnnyman727**
Adds the ability to request the Mac Address from the command line:

screen shot 2014-09-30 at 12 36 08 am

### CODE REVIEW

**Comment by kocsenc** [comment]
I know this is old, but I couldn't find how to do this with `t2` for my tessel 2 wifi.

**Comment by johnnyman727** [comment]
@kocsenc I've been able to use the [`getmac`](https://www.npmjs.com/package/getmac) module on T2. You'll have to deploy your project with the `--full` flag because of some issue that I haven't tracked down yet.

**Comment by kocsenc** [comment]
Sweet, thanks @johnnyman727. I'd be betting that the full flag is necessary to get the library pushed into the tessel.

**Comment by johnnyman727** [comment]
@kocsenc I debugged a bit and it looks like the issue that necessitates the `--full` flag is the strange way they export their modules. Issues [reported here](https://github.com/tessel/t2-cli/issues/734).

**Pull request merged**
