### PR TITLE
Adds Global and Local Configuration Variables

### PR DESCRIPTION
**Pull request by johnnyman727**
See [this RFC](https://forums.tessel.io/t/config-variables/1331) for the intended functionality.

@natevw can you check it over?

### CODE REVIEW

**Comment by johnnyman727** [comment]
Not ready yet: `tessel config unset` has a bug that I'll have to work out.

**Comment by johnnyman727** [comment]
This seems to be failing on Travis because it can't install libusb:
```
The following extra packages will be installed:
  libudev0 libusb-1.0-0
The following NEW packages will be installed:
  libudev-dev libusb-1.0-0 libusb-1.0-0-dev
The following packages will be upgraded:
  build-essential libudev0
2 upgraded, 3 newly installed, 0 to remove and 100 not upgraded.
Need to get 285 kB of archives.
After this operation, 1,555 kB of additional disk space will be used.
Err http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libudev0 amd64 175-0ubuntu9.8
  404  Not Found [IP: 2001:67c:1562::16 80]
Get:1 http://us.archive.ubuntu.com/ubuntu/ precise/main libusb-1.0-0 amd64 2:1.0.9~rc3-2ubuntu1 [31.0 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main build-essential amd64 11.5ubuntu2.1 [5,816 B]
Err http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libudev-dev amd64 175-0ubuntu9.8
  404  Not Found [IP: 2001:67c:1562::16 80]
Get:3 http://us.archive.ubuntu.com/ubuntu/ precise/main libusb-1.0-0-dev amd64 2:1.0.9~rc3-2ubuntu1 [158 kB]
Fetched 195 kB in 0s (2,122 kB/s)
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/u/udev/libudev0_175-0ubuntu9.8_amd64.deb  404  Not Found [IP: 2001:67c:1562::16 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/u/udev/libudev-dev_175-0ubuntu9.8_amd64.deb  404  Not Found [IP: 2001:67c:1562::16 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command "sudo apt-get install pkg-config build-essential libusb-1.0-0-dev libudev-dev" failed and exited with 100 during .
```

**Comment by kevinmehall** [comment]
Uh, that seems to be an issue on Travis's side.

**Comment by johnnyman727** [comment]
This is pretty stale and not useful for anyone's project so I'm closing for now.

**Pull request closed without merging**
